/* The line under the name. One is drawn at random on every visit.
   Keep them in this register: lowercase, short, flat, no punctuation, nothing clever. */
window.LINES = [
  "man living in world",
  "man goes to work",
  "everyone is fine",
  "he is doing great",
  "another good year",
  "the numbers are in",
  "everything is on schedule",
  "the lights stay on all night",
  "the city is awake and so is he",
  "he checked his phone again",
  "the office is open plan",
  "the elevator is full of people going up",
  "he made it",
  "promoted again",
  "he got what he wanted",
  "the plan worked",
  "the goal was reached and nothing happened",
  "next quarter will be bigger",
  "he wanted more and got it",
  "the ladder goes up and up",
  "he arrived and kept going",
  "success looks like this",
  "the raise came through",
  "the title is on the door",
  "the corner office faces a wall",
  "the winner keeps running",
  "he is the best at it now",
  "they gave him a plaque",
  "the bonus was large",
  "rich man in a fast car",
  "the car is fast and the road ends",
  "the prize is another race",
  "he won and went home",
  "he could do anything and did this",
  "free to go anywhere and staying here",
  "no one is stopping him",
  "the door is open",
  "nobody told him what to do",
  "he can leave whenever he wants",
  "all the choices were his",
  "free man in a parked car",
  "a wide road at night",
  "no rules and nothing to do",
  "nobody kneels anymore",
  "the church is a condo now",
  "the old ways were sold",
  "his father would not recognize this",
  "there is no one to ask",
  "nothing was handed down",
  "the ritual was skipped this year",
  "the old house is a parking lot",
  "what was sacred is on sale",
  "the family dinner is a group text",
  "everything is going well",
  "it is what it is",
  "fine thanks",
  "he smiled for the photo",
  "the suit still fits",
  "someone is screaming somewhere",
  "the sun comes up on the parking lot",
  "the highway goes both ways",
  "a good man in a good job",
  "he has everything and it is quiet",
  "the alarm goes off and he goes",
  "he is on his way up",
  "the American dream is fully furnished",
  "the meeting ran long",
  "the view from the top is more top",
  "a full tank and nowhere to be",
  "the country is open late",
  "he did everything right",
  "the future arrived and clocked in",
];
